# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\json_convertor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JsonConvertor(object):
    def setupUi(self, JsonConvertor):
        JsonConvertor.setObjectName("JsonConvertor")
        JsonConvertor.resize(1269, 782)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        JsonConvertor.setFont(font)
        self.centralwidget = QtWidgets.QWidget(JsonConvertor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_File_Name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_File_Name.setFont(font)
        self.label_File_Name.setObjectName("label_File_Name")
        self.verticalLayout.addWidget(self.label_File_Name)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidgetLoadJson = QtWidgets.QTreeWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidgetLoadJson.sizePolicy().hasHeightForWidth())
        self.treeWidgetLoadJson.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidgetLoadJson.setFont(font)
        self.treeWidgetLoadJson.setStyleSheet("QTreeWidget {\n"
"    font-family: \"Nimbus Mono PS [urw]\";\n"
"    font-size: 13pt;\n"
"    font-weight: bold;\n"
"    background-color: #ffffff; /* Белый фон */\n"
"    border: 1px solid #000000; /* Серая рамка */\n"
"    border-radius: 5px;\n"
"}\n"
"QTreeWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"QTreeWidget::item:selected {\n"
"    background-color: #007acc; /* Синий фон для выделенного элемента */\n"
"    color: white; /* Белый текст для выделенного элемента */\n"
"}\n"
"")
        self.treeWidgetLoadJson.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeWidgetLoadJson.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeWidgetLoadJson.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.treeWidgetLoadJson.setObjectName("treeWidgetLoadJson")
        self.horizontalLayout.addWidget(self.treeWidgetLoadJson)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        JsonConvertor.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(JsonConvertor)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1269, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuFiles = QtWidgets.QMenu(self.menuBar)
        self.menuFiles.setObjectName("menuFiles")
        JsonConvertor.setMenuBar(self.menuBar)
        self.actionAdd_json_file = QtWidgets.QAction(JsonConvertor)
        self.actionAdd_json_file.setObjectName("actionAdd_json_file")
        self.actionSave_json_file = QtWidgets.QAction(JsonConvertor)
        self.actionSave_json_file.setObjectName("actionSave_json_file")
        self.menuFiles.addAction(self.actionAdd_json_file)
        self.menuFiles.addAction(self.actionSave_json_file)
        self.menuBar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(JsonConvertor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(JsonConvertor)

    def retranslateUi(self, JsonConvertor):
        _translate = QtCore.QCoreApplication.translate
        JsonConvertor.setWindowTitle(_translate("JsonConvertor", "Json Convertor"))
        self.label_File_Name.setText(_translate("JsonConvertor", "example.json"))
        self.treeWidgetLoadJson.headerItem().setText(0, _translate("JsonConvertor", "Load Json File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("JsonConvertor", "Loaded file for editing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("JsonConvertor", "Import edited file"))
        self.menuFiles.setTitle(_translate("JsonConvertor", "Files"))
        self.actionAdd_json_file.setText(_translate("JsonConvertor", "Add json file"))
        self.actionSave_json_file.setText(_translate("JsonConvertor", "Save json file"))
