# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rusla\Desktop\Web_Scrapper-main\Web_Scrapper-main\ui\scraper_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1509, 787)
        MainWindow.setStyleSheet("/* Основное окно и вкладки */\n"
"QMainWindow {\n"
"    background-color: #f4f7f6;\n"
"    color: #222831;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #ffffff;\n"
"    color: #222831;\n"
"    padding: 8px 15px;\n"
"    border: 1px solid #dddddd;\n"
"    border-radius: 6px;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #00adb5;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Кнопки */\n"
"QPushButton {\n"
"    background-color: #00adb5;\n"
"    color: white;\n"
"    padding: 6px 15px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #028a91;\n"
"}\n"
"\n"
"/* Поля ввода */\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #ffffff;\n"
"    color: #222831;\n"
"    border: 1px solid #dddddd;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"/* Таблица и списки */\n"
"QTableWidget, QListWidget {\n"
"    background-color: #ffffff;\n"
"    color: #222831;\n"
"    gridline-color: #f0f0f0;\n"
"    border: 1px solid #dddddd;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* Логи */\n"
"QTextBrowser {\n"
"    background-color: #ffffff;\n"
"    color: #222831;\n"
"    border: 1px solid #dddddd;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* ===== ДОПОЛНЕНИЯ ===== */\n"
"\n"
"/* Label (подписи и текст) */\n"
"QLabel {\n"
"    color: #393e46;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* CheckBox */\n"
"QCheckBox {\n"
"    color: #222831;\n"
"    padding: 3px;\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 3px;\n"
"    border: 1px solid #00adb5;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #00adb5;\n"
"    border: none;\n"
"}\n"
"\n"
"/* ComboBox */\n"
"QComboBox {\n"
"    background-color: #ffffff;\n"
"    color: #222831;\n"
"    border: 1px solid #dddddd;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ffffff;\n"
"    selection-background-color: #00adb5;\n"
"    selection-color: #ffffff;\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QToolBar::separator {\n"
"    background-color: #333333;  /* Тёмно-серый / почти чёрный */\n"
"    width: 2px;\n"
"    margin: 4px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1331, 741))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tasks_table = QtWidgets.QTableWidget(self.tab)
        self.tasks_table.setGeometry(QtCore.QRect(0, 0, 1331, 701))
        self.tasks_table.setObjectName("tasks_table")
        self.tasks_table.setColumnCount(11)
        self.tasks_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(10, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_scanner = QtWidgets.QWidget()
        self.tab_scanner.setObjectName("tab_scanner")
        self.btn_scan = QtWidgets.QPushButton(self.tab_scanner)
        self.btn_scan.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.btn_scan.setObjectName("btn_scan")
        self.btn_dns_scan = QtWidgets.QPushButton(self.tab_scanner)
        self.btn_dns_scan.setGeometry(QtCore.QRect(130, 10, 111, 31))
        self.btn_dns_scan.setObjectName("btn_dns_scan")
        self.btn_certificate_scan = QtWidgets.QPushButton(self.tab_scanner)
        self.btn_certificate_scan.setGeometry(QtCore.QRect(60, 50, 131, 31))
        self.btn_certificate_scan.setObjectName("btn_certificate_scan")
        self.tabWidget.addTab(self.tab_scanner, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_exploit = QtWidgets.QWidget()
        self.tab_exploit.setObjectName("tab_exploit")
        self.tabWidgetExploits = QtWidgets.QTabWidget(self.tab_exploit)
        self.tabWidgetExploits.setGeometry(QtCore.QRect(10, 0, 1271, 691))
        self.tabWidgetExploits.setObjectName("tabWidgetExploits")
        self.tabGeneralExploits = QtWidgets.QWidget()
        self.tabGeneralExploits.setObjectName("tabGeneralExploits")
        self.btnClear = QtWidgets.QPushButton(self.tabGeneralExploits)
        self.btnClear.setGeometry(QtCore.QRect(630, 370, 111, 31))
        self.btnClear.setObjectName("btnClear")
        self.btnRun = QtWidgets.QPushButton(self.tabGeneralExploits)
        self.btnRun.setGeometry(QtCore.QRect(510, 370, 111, 31))
        self.btnRun.setObjectName("btnRun")
        self.btnCheck = QtWidgets.QPushButton(self.tabGeneralExploits)
        self.btnCheck.setGeometry(QtCore.QRect(390, 370, 111, 31))
        self.btnCheck.setObjectName("btnCheck")
        self.label = QtWidgets.QLabel(self.tabGeneralExploits)
        self.label.setGeometry(QtCore.QRect(370, 25, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tabGeneralExploits)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtExploitMeta = QtWidgets.QTextEdit(self.tabGeneralExploits)
        self.txtExploitMeta.setGeometry(QtCore.QRect(390, 70, 351, 291))
        self.txtExploitMeta.setObjectName("txtExploitMeta")
        self.listWidgetExploits = QtWidgets.QListWidget(self.tabGeneralExploits)
        self.listWidgetExploits.setGeometry(QtCore.QRect(0, 30, 371, 371))
        self.listWidgetExploits.setObjectName("listWidgetExploits")
        self.lineEditTarget = QtWidgets.QLineEdit(self.tabGeneralExploits)
        self.lineEditTarget.setGeometry(QtCore.QRect(470, 30, 271, 24))
        self.lineEditTarget.setObjectName("lineEditTarget")
        self.tabWidgetExploits.addTab(self.tabGeneralExploits, "")
        self.tabBrowserXSS = QtWidgets.QWidget()
        self.tabBrowserXSS.setObjectName("tabBrowserXSS")
        self.lineEditXssTarget = QtWidgets.QLineEdit(self.tabBrowserXSS)
        self.lineEditXssTarget.setGeometry(QtCore.QRect(470, 30, 271, 24))
        self.lineEditXssTarget.setObjectName("lineEditXssTarget")
        self.plainTextPayload = QtWidgets.QPlainTextEdit(self.tabBrowserXSS)
        self.plainTextPayload.setGeometry(QtCore.QRect(0, 30, 371, 371))
        self.plainTextPayload.setObjectName("plainTextPayload")
        self.btnRunXss = QtWidgets.QPushButton(self.tabBrowserXSS)
        self.btnRunXss.setGeometry(QtCore.QRect(390, 370, 111, 31))
        self.btnRunXss.setObjectName("btnRunXss")
        self.chkHeadless = QtWidgets.QCheckBox(self.tabBrowserXSS)
        self.chkHeadless.setGeometry(QtCore.QRect(510, 370, 91, 31))
        self.chkHeadless.setObjectName("chkHeadless")
        self.textEdit = QtWidgets.QTextEdit(self.tabBrowserXSS)
        self.textEdit.setGeometry(QtCore.QRect(390, 90, 351, 271))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.lbl_payload = QtWidgets.QLabel(self.tabBrowserXSS)
        self.lbl_payload.setGeometry(QtCore.QRect(0, 5, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.lbl_payload.setFont(font)
        self.lbl_payload.setObjectName("lbl_payload")
        self.lbl_target = QtWidgets.QLabel(self.tabBrowserXSS)
        self.lbl_target.setGeometry(QtCore.QRect(390, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.lbl_target.setFont(font)
        self.lbl_target.setObjectName("lbl_target")
        self.lineEditParamName = QtWidgets.QLineEdit(self.tabBrowserXSS)
        self.lineEditParamName.setGeometry(QtCore.QRect(470, 60, 271, 22))
        self.lineEditParamName.setObjectName("lineEditParamName")
        self.lbl_params = QtWidgets.QLabel(self.tabBrowserXSS)
        self.lbl_params.setGeometry(QtCore.QRect(390, 60, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.lbl_params.setFont(font)
        self.lbl_params.setObjectName("lbl_params")
        self.btnXssHelp = QtWidgets.QPushButton(self.tabBrowserXSS)
        self.btnXssHelp.setGeometry(QtCore.QRect(620, 370, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.btnXssHelp.setFont(font)
        self.btnXssHelp.setObjectName("btnXssHelp")
        self.tabWidgetExploits.addTab(self.tabBrowserXSS, "")
        self.tabWidget.addTab(self.tab_exploit, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lbl_export_settings = QtWidgets.QLabel(self.tab_2)
        self.lbl_export_settings.setGeometry(QtCore.QRect(0, 10, 61, 21))
        self.lbl_export_settings.setObjectName("lbl_export_settings")
        self.btn_export_data = QtWidgets.QPushButton(self.tab_2)
        self.btn_export_data.setGeometry(QtCore.QRect(0, 120, 121, 31))
        self.btn_export_data.setObjectName("btn_export_data")
        self.cmb_export_format = QtWidgets.QComboBox(self.tab_2)
        self.cmb_export_format.setGeometry(QtCore.QRect(50, 10, 151, 23))
        self.cmb_export_format.setObjectName("cmb_export_format")
        self.cmb_export_format.addItem("")
        self.cmb_export_format.addItem("")
        self.cmb_export_format.addItem("")
        self.table_data_preview = QtWidgets.QTableWidget(self.tab_2)
        self.table_data_preview.setGeometry(QtCore.QRect(0, 150, 1231, 571))
        self.table_data_preview.setObjectName("table_data_preview")
        self.table_data_preview.setColumnCount(0)
        self.table_data_preview.setRowCount(0)
        self.btn_data_preview = QtWidgets.QPushButton(self.tab_2)
        self.btn_data_preview.setGeometry(QtCore.QRect(140, 120, 121, 31))
        self.btn_data_preview.setObjectName("btn_data_preview")
        self.btn_browse_path = QtWidgets.QPushButton(self.tab_2)
        self.btn_browse_path.setGeometry(QtCore.QRect(750, 30, 151, 31))
        self.btn_browse_path.setObjectName("btn_browse_path")
        self.lbl_data_preview = QtWidgets.QLabel(self.tab_2)
        self.lbl_data_preview.setGeometry(QtCore.QRect(0, 40, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.lbl_data_preview.setFont(font)
        self.lbl_data_preview.setObjectName("lbl_data_preview")
        self.lbl_export_path = QtWidgets.QLabel(self.tab_2)
        self.lbl_export_path.setGeometry(QtCore.QRect(410, 40, 311, 16))
        self.lbl_export_path.setObjectName("lbl_export_path")
        self.lbl_exported_path = QtWidgets.QLabel(self.tab_2)
        self.lbl_exported_path.setGeometry(QtCore.QRect(0, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.lbl_exported_path.setFont(font)
        self.lbl_exported_path.setObjectName("lbl_exported_path")
        self.lbl_success_exported = QtWidgets.QLabel(self.tab_2)
        self.lbl_success_exported.setGeometry(QtCore.QRect(410, 70, 311, 16))
        self.lbl_success_exported.setObjectName("lbl_success_exported")
        self.check_flat_table = QtWidgets.QCheckBox(self.tab_2)
        self.check_flat_table.setGeometry(QtCore.QRect(210, 10, 141, 20))
        self.check_flat_table.setObjectName("check_flat_table")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.checkBox = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox.setGeometry(QtCore.QRect(0, 0, 111, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_2.setGeometry(QtCore.QRect(0, 30, 181, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_3.setGeometry(QtCore.QRect(0, 60, 141, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.proxy_input = QtWidgets.QLineEdit(self.tab_3)
        self.proxy_input.setGeometry(QtCore.QRect(180, 30, 231, 23))
        self.proxy_input.setObjectName("proxy_input")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(180, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.check_proxy_button = QtWidgets.QPushButton(self.tab_3)
        self.check_proxy_button.setGeometry(QtCore.QRect(180, 60, 231, 31))
        self.check_proxy_button.setObjectName("check_proxy_button")
        self.safe_button = QtWidgets.QPushButton(self.tab_3)
        self.safe_button.setGeometry(QtCore.QRect(0, 90, 131, 23))
        self.safe_button.setObjectName("safe_button")
        self.reset_button = QtWidgets.QPushButton(self.tab_3)
        self.reset_button.setGeometry(QtCore.QRect(0, 120, 131, 23))
        self.reset_button.setObjectName("reset_button")
        self.tabWidget.addTab(self.tab_3, "")
        self.lcd_total = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_total.setGeometry(QtCore.QRect(1330, 30, 64, 23))
        self.lcd_total.setObjectName("lcd_total")
        self.lcd_running = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_running.setGeometry(QtCore.QRect(1330, 90, 64, 23))
        self.lcd_running.setObjectName("lcd_running")
        self.lcd_success = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_success.setGeometry(QtCore.QRect(1330, 150, 64, 23))
        self.lcd_success.setObjectName("lcd_success")
        self.lcd_error = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_error.setGeometry(QtCore.QRect(1330, 210, 64, 23))
        self.lcd_error.setObjectName("lcd_error")
        self.lcd_stopped = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_stopped.setGeometry(QtCore.QRect(1330, 270, 64, 23))
        self.lcd_stopped.setObjectName("lcd_stopped")
        self.label_Task = QtWidgets.QLabel(self.centralwidget)
        self.label_Task.setGeometry(QtCore.QRect(1400, 30, 81, 21))
        self.label_Task.setObjectName("label_Task")
        self.label_Process = QtWidgets.QLabel(self.centralwidget)
        self.label_Process.setGeometry(QtCore.QRect(1400, 90, 81, 21))
        self.label_Process.setObjectName("label_Process")
        self.label_Sucessfull = QtWidgets.QLabel(self.centralwidget)
        self.label_Sucessfull.setGeometry(QtCore.QRect(1400, 150, 81, 21))
        self.label_Sucessfull.setObjectName("label_Sucessfull")
        self.label_Error = QtWidgets.QLabel(self.centralwidget)
        self.label_Error.setGeometry(QtCore.QRect(1400, 210, 81, 21))
        self.label_Error.setObjectName("label_Error")
        self.label_Stoped = QtWidgets.QLabel(self.centralwidget)
        self.label_Stoped.setGeometry(QtCore.QRect(1400, 270, 81, 21))
        self.label_Stoped.setObjectName("label_Stoped")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_add_task_2 = QtWidgets.QAction(MainWindow)
        self.action_add_task_2.setObjectName("action_add_task_2")
        self.action_del_task = QtWidgets.QAction(MainWindow)
        self.action_del_task.setObjectName("action_del_task")
        self.action_run_task = QtWidgets.QAction(MainWindow)
        self.action_run_task.setObjectName("action_run_task")
        self.action_manage_sessions = QtWidgets.QAction(MainWindow)
        self.action_manage_sessions.setObjectName("action_manage_sessions")
        self.action_save_session = QtWidgets.QAction(MainWindow)
        self.action_save_session.setObjectName("action_save_session")
        self.action_search_tasks = QtWidgets.QAction(MainWindow)
        self.action_search_tasks.setObjectName("action_search_tasks")
        self.action_run_selected_bulk = QtWidgets.QAction(MainWindow)
        self.action_run_selected_bulk.setObjectName("action_run_selected_bulk")
        self.action_delete_selected_bulk = QtWidgets.QAction(MainWindow)
        self.action_delete_selected_bulk.setObjectName("action_delete_selected_bulk")
        self.action_save_selected_bulk = QtWidgets.QAction(MainWindow)
        self.action_save_selected_bulk.setObjectName("action_save_selected_bulk")
        self.action_run_analytics = QtWidgets.QAction(MainWindow)
        self.action_run_analytics.setObjectName("action_run_analytics")
        self.action_open_calendar = QtWidgets.QAction(MainWindow)
        self.action_open_calendar.setObjectName("action_open_calendar")
        self.toolBar.addAction(self.action_add_task_2)
        self.toolBar.addAction(self.action_del_task)
        self.toolBar.addAction(self.action_delete_selected_bulk)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_run_task)
        self.toolBar.addAction(self.action_run_selected_bulk)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_save_selected_bulk)
        self.toolBar.addAction(self.action_save_session)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_manage_sessions)
        self.toolBar.addAction(self.action_search_tasks)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_run_analytics)
        self.toolBar.addAction(self.action_open_calendar)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidgetExploits.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tasks_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "№"))
        item = self.tasks_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "URL"))
        item = self.tasks_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Selectors"))
        item = self.tasks_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Methode"))
        item = self.tasks_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tasks_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Action"))
        item = self.tasks_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Save"))
        item = self.tasks_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Cookies"))
        item = self.tasks_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Params"))
        item = self.tasks_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Timer"))
        item = self.tasks_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Last Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Scraper"))
        self.btn_scan.setText(_translate("MainWindow", "Start Scan"))
        self.btn_dns_scan.setText(_translate("MainWindow", "DNS Scan"))
        self.btn_certificate_scan.setText(_translate("MainWindow", "Certificate scanner"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_scanner), _translate("MainWindow", "Scanner"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "CVE Analysis"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))
        self.btnRun.setText(_translate("MainWindow", "Run"))
        self.btnCheck.setText(_translate("MainWindow", "Check"))
        self.label.setText(_translate("MainWindow", "   Target:"))
        self.label_2.setText(_translate("MainWindow", "Avialable Exploits"))
        self.tabWidgetExploits.setTabText(self.tabWidgetExploits.indexOf(self.tabGeneralExploits), _translate("MainWindow", "General Exploits"))
        self.btnRunXss.setText(_translate("MainWindow", "Run in browser"))
        self.chkHeadless.setText(_translate("MainWindow", "Headless"))
        self.lbl_payload.setText(_translate("MainWindow", "XSS Payload"))
        self.lbl_target.setText(_translate("MainWindow", "Target:"))
        self.lbl_params.setText(_translate("MainWindow", "Params"))
        self.btnXssHelp.setText(_translate("MainWindow", "JS + DOM CRIB"))
        self.tabWidgetExploits.setTabText(self.tabWidgetExploits.indexOf(self.tabBrowserXSS), _translate("MainWindow", "Browser-based XSS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_exploit), _translate("MainWindow", "Exploits"))
        self.lbl_export_settings.setText(_translate("MainWindow", "Format:"))
        self.btn_export_data.setText(_translate("MainWindow", "Export"))
        self.cmb_export_format.setItemText(0, _translate("MainWindow", "JSON"))
        self.cmb_export_format.setItemText(1, _translate("MainWindow", "CSV"))
        self.cmb_export_format.setItemText(2, _translate("MainWindow", "XLSX"))
        self.btn_data_preview.setText(_translate("MainWindow", "Data Preview"))
        self.btn_browse_path.setText(_translate("MainWindow", "Browse (QFileDialog)"))
        self.lbl_data_preview.setText(_translate("MainWindow", "Export Path: "))
        self.lbl_export_path.setText(_translate("MainWindow", "[ C:/exports/data.json ]"))
        self.lbl_exported_path.setText(_translate("MainWindow", "Exported to: "))
        self.lbl_success_exported.setText(_translate("MainWindow", "[ C:/exports/data.json ]"))
        self.check_flat_table.setText(_translate("MainWindow", "Export in flat format"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Tasks History"))
        self.checkBox.setText(_translate("MainWindow", "Dark Theme"))
        self.checkBox_2.setText(_translate("MainWindow", "Auto-saved after parsing"))
        self.checkBox_3.setText(_translate("MainWindow", "Use proxy rotation"))
        self.label_3.setText(_translate("MainWindow", "Type proxy(optional)"))
        self.check_proxy_button.setText(_translate("MainWindow", "Check proxy"))
        self.safe_button.setText(_translate("MainWindow", "Safe settings"))
        self.reset_button.setText(_translate("MainWindow", "Reset to default"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Settings"))
        self.label_Task.setText(_translate("MainWindow", "All Tasks"))
        self.label_Process.setText(_translate("MainWindow", "In Process"))
        self.label_Sucessfull.setText(_translate("MainWindow", "Sucessfull"))
        self.label_Error.setText(_translate("MainWindow", "ERROR"))
        self.label_Stoped.setText(_translate("MainWindow", "Stoped"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_add_task_2.setText(_translate("MainWindow", "+ Add Task"))
        self.action_add_task_2.setToolTip(_translate("MainWindow", "Add Task"))
        self.action_del_task.setText(_translate("MainWindow", "🗑 Delete\n"
""))
        self.action_run_task.setText(_translate("MainWindow", "▶ Run Task\n"
""))
        self.action_manage_sessions.setText(_translate("MainWindow", "📁 Session"))
        self.action_save_session.setText(_translate("MainWindow", "💾 Save Session"))
        self.action_search_tasks.setText(_translate("MainWindow", "🔍 Search"))
        self.action_run_selected_bulk.setText(_translate("MainWindow", "▶ Run Selected"))
        self.action_delete_selected_bulk.setText(_translate("MainWindow", "🗑 Delete Selected"))
        self.action_save_selected_bulk.setText(_translate("MainWindow", "💾 Save Selected"))
        self.action_run_analytics.setText(_translate("MainWindow", "📊 Create Graphics"))
        self.action_open_calendar.setText(_translate("MainWindow", "📆 Calendar"))
